package de.paul.voxelgame.core;

public enum MenuAction {
    NONE,
    RESUME,
    OPTIONS,
    EXIT,
    BACK,
    SENSITIVITY_DECREASE,
    SENSITIVITY_INCREASE,
    HUD_SCALE_DECREASE,
    HUD_SCALE_INCREASE,
    VIEW_DISTANCE_DECREASE,
    VIEW_DISTANCE_INCREASE,
    MUSIC_VOLUME_DECREASE,
    MUSIC_VOLUME_INCREASE,
    EFFECTS_VOLUME_DECREASE,
    EFFECTS_VOLUME_INCREASE,
    FULLSCREEN_TOGGLE,
    RESOLUTION_PREVIOUS,
    RESOLUTION_NEXT,
    LANGUAGE_TOGGLE
}
